export const
    CREATE_REQUEST = 'CREATE_REQUEST',
    CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS',
    CREATE_REQUEST_FAILURE = 'CREATE_REQUEST_FAILURE',

    GET_REQUEST = 'GET_REQUEST',
    GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS',
    GET_REQUEST_FAILURE = 'GET_REQUEST_FAILURE',

    SEND_EDITOR_VALUE = 'SEND_EDITOR_VALUE',

    EDITOR_CHANGE_SUCCESS = 'EDITOR_CHANGE_SUCCESS',
    EDITOR_CHANGE_FAILURE = 'EDITOR_CHANGE_FAILURE', 

    STEP_BACK = 'STEP_BACK',
    STEP_FORWARD = 'STEP_FORWARD'; 